openapi: 3.0.0
info:
  description: User Microservice (API)
  version: 1.0.0
  title: User API DOCS
servers:
  - url: /api/v1

paths:
  /user/{id}:
    $ref: "../routes/user.with.id.routes.yaml"
  /user:
    $ref: "../routes/user.routes.yaml"
  /users:
    $ref: "../routes/users.routes.yaml"
  /role:
    $ref: "../routes/role.routes.yaml"
  /roles:
    $ref: "../routes/roles.routes.yaml"
