# this file fulfills user requests on the /role path
get:
  summary: Returns a single role.
  operationId: findRole
  description: Role GET operation. uses additional parameters if provided.
  parameters:
    - in: query
      name: id
      schema:
        type: integer
      required: false
      description: Numeric id of the Role (Optional if codename is present)
    - in: query
      name: codename
      schema:
        type: string
      required: false
      description: String programmatic codename of the Role (Optional if id is present)
  tags:
    - Role
  responses:
    '200':
      description: Returns single role if found
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: number
              name:
                type: string
              codename:
                type: string
              description:
                type: string
              updatedAt:
                type: string
              createdAt:
                type: string
    default:
      $ref: "../api/responses/server-error.yaml"

post:
  summary: creates a new role
  operationId: createRole
  description: Creates a new role. Errors if unique constraint collision.
  tags:
    - Role
  requestBody:
    content:
      'application/json':
        schema:
          properties:
            name:
              description: role name
              type: string
            codename:
              description: static programmatic name, autogenerated if missing
              type: string
            description:
              description: role description
              type: string
          required:
            - name
            - description
  responses:
    '200':
      description: Returns created role record
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: number
              name:
                type: string
              codename:
                type: string
              description:
                type: string
              updatedAt:
                type: string
              createdAt:
                type: string
    default:
      $ref: "../api/responses/server-error.yaml"

put:
  summary: updates a role
  operationId: updateRole
  description: Updates a role. Errors if not found or permissions are wrong. schema fields passed in will be updated.
  tags:
    - Role
  requestBody:
    content:
      'application/json':
        schema:
          properties:
            id:
              description: user id
              type: number
            name:
              description: role name
              type: string
            description:
              description: description of role
              type: string
          required:
            - id
  responses:
    '200':
      description: Returns updated role record
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: number
              name:
                type: string
              codename:
                type: string
              description:
                type: string
              updatedAt:
                type: string
              createdAt:
                type: string
    default:
      $ref: "../api/responses/server-error.yaml"
