# this file fulfills routes on the /users path
get:
  summary: Returns a list of all the users.
  operationId: getAllUsers
  description: Test for the api GET operation
  tags:
    - User
  responses:
    '200':
      description: Some sort of data that verifies the scaffold works
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: number
              username:
                type: string
              firstname:
                type: string
              lastname:
                type: string
              updatedAt:
                type: string
              createdAt:
                type: string
    default:
      $ref: "../api/responses/server-error.yaml"
