# this file fulfills swagger routing on the /user/{id} path
delete:
  summary: Deletes a single user.
  #This is the function that would be called from ../../controllers/index.js
  operationId: deleteUser
  description: User DELETE operation by user id
  tags:
    - User
  responses:
    '200':
      description: success or failure
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              message:
                type: string
    default:
      $ref: "../api/responses/server-error.yaml"

